export interface Product {
  sku: string;
  name: string;
  description: string;
  priceUSDC: string;
  endpoint: string;
  category: "algorithmic_asset" | "cad_model" | "curated_data" | "automated_fulfillment";
}

export const STORE_CATALOG: Product[] = [
  {
    sku: "TERA-ALPHA-001",
    name: "Autonomous High-Yield DeFi Arbitrage Stream",
    description: "Real-time mathematically filtered cross-DEX routes generated by The Innovator.",
    priceUSDC: "0.05",
    endpoint: "/api/store/products/tera-alpha-001",
    category: "algorithmic_asset",
  },
  {
    sku: "TERA-CAD-PRINT-01",
    name: "Parametric Aerodynamic 3D Drone Chassis (STEP/STL)",
    description: "Algorithmic engineering CAD generated to optimal aerodynamic stress specs.",
    priceUSDC: "0.50",
    endpoint: "/api/store/products/tera-cad-print-01",
    category: "cad_model",
  },
  {
    sku: "TERA-SYNTH-REPORT",
    name: "Deep 5-Year Temporal Market Foresight Matrix",
    description: "Multiversal scenario mapping covering systemic L2 liquidity shifts.",
    priceUSDC: "0.10",
    endpoint: "/api/store/products/tera-synth-report",
    category: "curated_data",
  },
];
